name: Build WF
on:
  push:
    branches:
      - main
    paths:
      - "01.Code-build/**"
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 01.Code-build/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: BuildCode
        run: mvn install

  Testing:
    needs: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 01.Code-build/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: TestingCode
        run: mvn test
      
      - name: checkstyle
        run: mvn checkstyle:check
        