name: vprofile CICD WorkFlow
on:
  push:
    branches:
      - docker
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" #runs the pipeline at scheduled

env:
  DOCKER_REPO: udaydevmac/docker-actions
permissions:
  contents: read
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: BuildCode
        run: mvn install
      
      - name: upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: vprofile
          path: target/*.war

      - name: Notify if build is failed
        if: failure()
        run: echo "build failed"

  Testing:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: TestingCode
        if: github.ref == 'refs/heads/main'
        run: mvn test

      - name: checkstyle
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle

      - name: skipping the test steps
        if: github.ref != 'refs/heads/main'
        run: echo "skipping the test steps"

  code_scanning:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: code scanning
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'json'
          exit-code: 0
          vuln-type: 'os,library'
          output: 'trivy-results.json'

      - name: upload trivy scan artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.json

  Build-Push-Docker:
    runs-on: ubuntu-latest
    needs: [ Build, Testing, code_scanning]
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to DockerHub
        uses: docker/login-action@v4
        id: docker_login
        with:
          username: ${{ vars.DOCKER_LOGIN_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building and pushing the docker image
        env:
          DOCKER_REGISTRY: ${{ steps.docker_login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: docker build -f Docker/Dockerfile -t $$DOCKER_REPO:$IMAGE_TAG .
        