name: Terraform
on:
  push:
    branches:
      - terrraform

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: aws config
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: set up terrraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: '1.4.0'

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Terraform Format'
        uses: 'terraform-linters/setup-tflint@v1'
        with:
          tflint_version: 'v0.30.0'

      - name: 'Terraform Init'
        run: 'terraform init'

      - name: 'Terraform Validate'
        run: 'terraform validate -no-color'

      - name: 'Terraform Plan'
        run: 'terraform plan -no-color -input=false'

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/terraform' && github.event_name == 'push'
        run: 'terraform apply -no-color -auto-approve'